(require 'package)
(setq package-enable-at-startup nil)
(package-initialize)

(require 'org)
(require 'ox)
(require 'ox-beamer)
(require 'ox-latex)
(require 'cl)
(require 'org-capture)
(require 'org-id)
(require 'ob-clojure)
(require 'ob-haskell)
(setq org-export-async-debug nil)
